### ISSUE TITLE
Sometimes api.jslinterrors.com returns a Not Found error

### ISSUE THREAD

**Issue by nicolo-ribaudo** [jamesallardice/jslint-error-explanations#32]
If there is a variable in the error message which is longer than two character, you'll get a Not Found error.

http://api.jslinterrors.com/explain?message=%27ab%27%20is%20not%20defined. - Works
http://api.jslinterrors.com/explain?message=%27abc%27%20is%20not%20defined. - Doesn't work

**Comment by jamesallardice** [comment]
Thanks for reporting that, it's very strange. I'll try to get that fixed ASAP.

**Comment by jamesallardice** [comment]
This should be resolved now. Please let me know if you have any other issues. Thanks again!
