### ISSUE TITLE
Website search is broken

### ISSUE THREAD

**Issue by gilluminate** [jamesallardice/jslint-error-explanations#34]

**Comment by jamesallardice** [comment]
Do you have any more detail? It does not appear to be broken to me. If I [search for "already defined"](http://jslinterrors.com/?q=already+defined) I get one result, "{a} is already defined".

**Comment by gilluminate** [comment]
I realize now that I was searching on the option name that would cause the message rather than the error message itself. May be useful as a feature request. Not a bug though.
