### ISSUE TITLE
Repository description still lists the old website link

### ISSUE THREAD

**Issue by per1234** [jamesallardice/jslint-error-explanations#42]
From https://github.com/jamesallardice/jslint-error-explanations:
>📝 Explanations of all the (sometimes cryptic) error messages thrown by JSLint and JSHint http://jslinterrors.com

Should be changed to:
>📝 Explanations of all the (sometimes cryptic) error messages thrown by JSLint and JSHint http://linterrors.com/

**Comment by jamesallardice** [comment]
Another good spot, changed that now. Thanks 👍
